//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMedicamento
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicamentoCLS", Namespace="http://schemas.datacontract.org/2004/07/ServiciosMedicamento.Clases")]
    public partial class MedicamentoCLS : object
    {
        
        private int iidmedicamentoField;
        
        private string nombreField;
        
        private string concentracionField;
        
        private int iidformafarmaceuticaField;
        
        private string nombreFormaFarmaceuticaField;
        
        private decimal precioField;
        
        private int stockField;
        
        private string presentacionField;
        
        private int bhabilitadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iidmedicamento
        {
            get
            {
                return this.iidmedicamentoField;
            }
            set
            {
                this.iidmedicamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string concentracion
        {
            get
            {
                return this.concentracionField;
            }
            set
            {
                this.concentracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iidformafarmaceutica
        {
            get
            {
                return this.iidformafarmaceuticaField;
            }
            set
            {
                this.iidformafarmaceuticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string nombreFormaFarmaceutica
        {
            get
            {
                return this.nombreFormaFarmaceuticaField;
            }
            set
            {
                this.nombreFormaFarmaceuticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string presentacion
        {
            get
            {
                return this.presentacionField;
            }
            set
            {
                this.presentacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int bhabilitado
        {
            get
            {
                return this.bhabilitadoField;
            }
            set
            {
                this.bhabilitadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaFarmaceuticaCLS", Namespace="http://schemas.datacontract.org/2004/07/ServiciosMedicamento.Clases")]
    public partial class FormaFarmaceuticaCLS : object
    {
        
        private int iidformafarmaceuticaField;
        
        private string nombreFormaFarmaceuticaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iidformafarmaceutica
        {
            get
            {
                return this.iidformafarmaceuticaField;
            }
            set
            {
                this.iidformafarmaceuticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreFormaFarmaceutica
        {
            get
            {
                return this.nombreFormaFarmaceuticaField;
            }
            set
            {
                this.nombreFormaFarmaceuticaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMedicamento.IMedicamentos")]
    public interface IMedicamentos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarMedicamentos", ReplyAction="http://tempuri.org/IMedicamentos/listarMedicamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceMedicamento.MedicamentoCLS>> listarMedicamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarFormaFarmaceutica", ReplyAction="http://tempuri.org/IMedicamentos/listarFormaFarmaceuticaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceMedicamento.FormaFarmaceuticaCLS>> listarFormaFarmaceuticaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/recuperarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/recuperarMedicamentoResponse")]
        System.Threading.Tasks.Task<ServiceMedicamento.MedicamentoCLS> recuperarMedicamentoAsync(int iidmedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/registrarYActualizarMedicamentos", ReplyAction="http://tempuri.org/IMedicamentos/registrarYActualizarMedicamentosResponse")]
        System.Threading.Tasks.Task<int> registrarYActualizarMedicamentosAsync(ServiceMedicamento.MedicamentoCLS oidmedicamentoCLS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/eliminarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/eliminarMedicamentoResponse")]
        System.Threading.Tasks.Task<int> eliminarMedicamentoAsync(int iidMedicamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMedicamentosChannel : ServiceMedicamento.IMedicamentos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MedicamentosClient : System.ServiceModel.ClientBase<ServiceMedicamento.IMedicamentos>, ServiceMedicamento.IMedicamentos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MedicamentosClient() : 
                base(MedicamentosClient.GetDefaultBinding(), MedicamentosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMedicamentos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MedicamentosClient(EndpointConfiguration endpointConfiguration) : 
                base(MedicamentosClient.GetBindingForEndpoint(endpointConfiguration), MedicamentosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MedicamentosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MedicamentosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MedicamentosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MedicamentosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MedicamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceMedicamento.MedicamentoCLS>> listarMedicamentosAsync()
        {
            return base.Channel.listarMedicamentosAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceMedicamento.FormaFarmaceuticaCLS>> listarFormaFarmaceuticaAsync()
        {
            return base.Channel.listarFormaFarmaceuticaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceMedicamento.MedicamentoCLS> recuperarMedicamentoAsync(int iidmedicamento)
        {
            return base.Channel.recuperarMedicamentoAsync(iidmedicamento);
        }
        
        public System.Threading.Tasks.Task<int> registrarYActualizarMedicamentosAsync(ServiceMedicamento.MedicamentoCLS oidmedicamentoCLS)
        {
            return base.Channel.registrarYActualizarMedicamentosAsync(oidmedicamentoCLS);
        }
        
        public System.Threading.Tasks.Task<int> eliminarMedicamentoAsync(int iidMedicamento)
        {
            return base.Channel.eliminarMedicamentoAsync(iidMedicamento);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMedicamentos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMedicamentos))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.3:8081/IMedicamentos.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MedicamentosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMedicamentos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MedicamentosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMedicamentos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMedicamentos,
        }
    }
}
